### ISSUE TITLE
Need plotDiet() function for mizerMR

### ISSUE THREAD

**Issue by kjmurph** [sizespectrum/mizerMR#3]
Using mzerHowTo::plotDiet2() to visualise the diet proportions from a sim object created using a setMultipleResources() param object, the original 'Resource' is the only resource being plotted, rather than the new Resource 1 and Resource 2 etc...

I am playing around with the functions to see if I can get them working, but this seems like a general bug that needs addressing for the master branch of mizerMR.

**Comment by gustavdelius** [comment]
Hi Kieran, you are quite right that mizerMR needs its own `plotDiet()` function, overwriting the core mizer `plotDiet()` function. It should be implemented similarly to how `plotSpectra()` is implemented. I believe that @baldrech is also working on this.

**Comment by kjmurph** [comment]
Hi Gustav. That's great, thank you! And thank you for all the great blog posts explaining the recent advances, very exciting progress!

**Comment by gustavdelius** [comment]
And in addition to `plotDiet()` we of course need to also mask `getDiet()`.

**Comment by gustavdelius** [comment]
@baldrech and I had a discussion about this and noticed that the easiest solution would be for `setMultipleResources()` to set the `intitial_n_pp` slot to zero so that it would not give any contributions to `getDiet()`. Then `getDiet()` should already work fine with mizerMR and only `plotDiet()` needs to be overwritten by mizerMR to also plot the MR resources.

**Comment by baldrech** [comment]
I think we can close this issue now thanks to pull request #7 ?

**Comment by gustavdelius** [comment]
Yes, I am closing this now but I have opened a new issue #9
